- name: Install latest Cockpit
  yum:
    name: 
      - storaged
      - cockpit
      - cockpit-storaged
      - pcp
    state: latest
- name: Start Cockpit
  service:
    name: cockpit
    state: started
    enabled: true
- name: Enable cockpit socket
  service:
    name: cockpit.socket
    state: started
    enabled: true
