- name: Install curl socat openssl crontabs
  yum:
    name: 
      - curl
      - socat
      - crontabs
      - openssl
    state: latest 
- name: Install acme.sh
  shell:
    cmd: curl https://get.acme.sh | sh
  args:
    warn: no
