---
- hosts: webservers
  remote_user: root
  vars: 
    domain_name: "bot.hxp.plus"
  tasks:
    - name: Install latest Nginx
      yum:
        name: nginx
        state: latest
    - name: Install curl socat openssl crontabs
      yum:
        name: 
          - curl
          - socat
          - crontabs
          - openssl
        state: latest
    - name: Create index page
      template:
        src: files/index.html.j2
        dest: /usr/share/nginx/html/index.html
    - name: Create nginx.conf
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
    - name: Start and Enable Nginx
      service:
        name: nginx
        state: started
        enabled: true
    - name: Start firewalld
      service: 
        name: firewalld
        state: started
        enabled: true
    - name: Add http service in firewalld
      firewalld:
        zone: public
        service: http
        permanent: yes
        state: enabled
        immediate: yes
    - name: Install acme.sh
      shell:
        cmd: curl https://get.acme.sh | sh
      args:
        warn: no
    - name: Create directory for certs
      file:
        path: /etc/pki/nginx/{{ domain_name }}
        state: directory
        mode: '0755'
    - name: Add http nginx configuration
      template: src=files/nginx.http.conf.j2 dest=/etc/nginx/conf.d/{{ domain_name }}.http.conf owner=nginx group=nginx mode=0644
    - name: reload nginx
      service: name=nginx state=reloaded
    - name: Issue cert
      shell:
        cmd: /root/.acme.sh/acme.sh --issue -d {{ domain_name }} --nginx --force
    - name: Install cert
      shell: /root/.acme.sh/acme.sh --install-cert -d {{ domain_name }} --key-file /etc/pki/nginx/{{ domain_name }}/key.pem --fullchain-file /etc/pki/nginx/{{ domain_name }}/cert.pem
    - name: Add https service in firewalld
      firewalld:
        zone: public
        service: https
        permanent: yes
        state: enabled
        immediate: yes
    - name: Add https nginx configuration
      template: src=files/nginx.https.conf.j2 dest=/etc/nginx/conf.d/{{ domain_name }}.https.conf owner=nginx group=nginx mode=0644
    - name: reload nginx
      service: name=nginx state=reloaded
